name: goaccess
services:
  goaccess:
    command:
      - /app/app.py
    container_name: goaccess
    depends_on:
      - initgeodb
      - redis
    healthcheck:
      test:
        - CMD
        - curl
        - -4sf
        - http://localhost:3050/health
      timeout: 10s
      interval: 1m0s
      retries: 3
      start_period: 15s
    image: goaccess_server
    networks:
      goaccess: null
    volumes:
      - /etc/goaccess/config.yaml:/etc/goaccess/config.yaml
      - type: volume
        source: goaccess_data
        target: /app/data
      - type: volume
        source: maxmind_geodata
        target: /app/geodb
        read_only: true
  initgeodb:
    container_name: initgeodb
    command:
      - /bin/sh
      - -c
      - |
        domain='https://download.db-ip.com';
        deadline=`date -d "1 week ago" +%s`;
        while IFS= read -r name; do
        filedate=`date +%s -r /var/geodb/dbip-$$name-lite-latest.mmdb 2>/dev/null || echo 0`;
        if [ "$$filedate" -lt "$$deadline" ]; then \
            wget -O - "$$domain/free/dbip-$$name-lite-20$$(date +%y)-$$(date +%m).mmdb.gz" | zcat 2>&1 | tee "/var/geodb/dbip-$$name-lite-latest.mmdb";
        fi;
        done <<EOF
        asn
        country
        EOF
    image: gitea.mango.local/gitea/ubuntu-custom:latest
    volumes:
      - type: volume
        source: maxmind_geodata
        target: /var/geodb
  redis:
    container_name: redis
    command:
      - redis-server
      - --save
      - "20"
      - "1"
      - --loglevel
      - notice
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "268435456"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 10s
    image: redis:6.2-alpine
    networks:
      goaccess: null
    volumes:
      - type: volume
        source: redis-cache
        target: /data
networks:
  goaccess:
    driver: bridge
    name: goaccess
volumes:
  goaccess_data:
    driver: local
    name: goaccess_data
  maxmind_geodata:
    driver: local
    name: maxmind_geodata
  redis-cache:
    driver: local
    name: redis-cache

