services:
  goaccess-debug:
    command: /app/tests/test.py
    build:
      context: .
      args: 
        debbuger: true
    image: goaccess-debug
    ports:
      - "3050:3050"
      - "5678:5678"
    volumes:
      - ./tests:/app/tests 
      - ./config.yaml:/app/config.yaml 
      - data:/app/data
    
volumes:
  data:
    driver: local