name: Build and Stage

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore:
     - '.gitea/**'
     - 'LICENSE'
     - 'README.md'

jobs:
  build:
    runs-on: orange-local

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: dev
          fetch-depth: 1

    - name: Set commit hash
      run: echo "HASH=$(echo $(git rev-parse HEAD) | cut -c1-10)" >> $GITEA_ENV
      
    - name: This build commit hash
      run: echo $HASH;

    - name: Build project
      run: docker build -t goaccess_server:$HASH .

  tag-n-push:
    runs-on: orange-local
    needs: build
    continue-on-error: true
    env:
      server: ${{ gitea.server_url }}
      imagename: goaccess_server
    steps:

      - run: docker logout "${server#https://}"

      - name: Login
        run: echo ${{secrets.ANSIBLE_API}} | docker login "${server#https://}" -u gitea --password-stdin

      - name: Tag remote image
        run: docker tag $imagename:$HASH "${server#https://}"/$user/$imagename:$HASH

      - name: Push latest
        run: docker push "${server#https://}"/$user/$imagename:$HASH

  start-container:
    runs-on: orange-local
    needs: build-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: dev
          fetch-depth: 1
          
    - name: Run stage server
      run: docker compose -f ./docker-compose.prod.yaml up -d

    - name: healthcheck
      run: |
        for i in {1..5}; do
          sleep 1.5
          res=$( docker inspect --format "{{json .State.Health }}" goaccess | jq .Status )
          if [ '"healthy"' = "$res" ]; then
            exit 0
          fi
        done
        docker logs goaccess
        exit 1

  run-tests:
    runs-on: orange-local
    needs: start-container
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: dev
          fetch-depth: 1

    - name: Test regex`es
      run: docker run --rm -it -v ./:/app py_tester:latest  /app/tests/test.py

    - name: Test API
      run: |
        docker run --add-host obne.goaccess.orange.local:$(ip -br addr show eth0 |awk '{print $3}' | cut -d'/' -f1) \
        --rm -it -v ./:/app py_tester:latest -m pytest  --disable-warnings  /app/tests/api_test.py
