name: Build and Stage
on:
  push:
    branches: [dev] 


jobs:
  build:
    name: Build
    runs-on: orange-local

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: docker build --no-cache -t goaccess_server:latest .

    - name: run stage server
      run: docker compose -f ./docker-compose.prod.yaml up -d

  test:
    name: test
    runs-on: orange-local

    steps:
    - name: test_modules
      run : docker run --rm -it  -v ~/goaccess_server:/app py_tester:latest  /app/tests/test.py

    - name: test_api
      run : docker run --rm -it  -v ~/goaccess_server:/app py_tester:latest -m pytest  --disable-warnings  /app/tests/api_test.py
      