name: Build and deploy
on:
  push:
    branches: [main]


jobs:
  build:
    name: Build and deploy
    runs-on: orange-local

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: docker build --no-cache -t goaccess_server:latest .

    - name: save image to archive
      run:  docker save goaccess_server:latest > ./goaccess_server.tar
        
    - name: copy archive to remote 
      run: rsync -azvhP  --info=progress2 ./goaccess_server.tar  orange:/home/orange/

    - name: copy to remote   
      run: rsync -azvhP  --info=progress2 ./{assets,docker-compose.prod.yaml} orange:/opt/goAccess_server
    
    - name: Add config
      run: ssh orange -t echo "GOACCESS_URL=${{vars.ORANGE_GOACCESS_URL}}" > /opt/goAccess_server/.config

    - name: Add config
      run: ssh orange -t echo "GOACCESS_OPTIONS=${{vars.ORANGE_GOACCESS_OPTIONS}}" >> /opt/goAccess_server/.config

    - name:  load image to remote 
      run: ssh orange -t docker image load -i goaccess_server.tar

    - name: restart app  
      run: ssh orange -t docker compose -f  /opt/goAccess_server/docker-compose.prod.yaml  up -d --no-deps

    - name: cleanup
      run: ssh orange -t rm /home/orange/goaccess_server.tar

