name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
     - '.gitea/**'
     - 'LICENSE'
     - 'README.md'

jobs:
  build:
    name: Build
    runs-on: orange-local
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: main
          fetch-depth: 1

    - name: Build project
      run: docker build --no-cache -t goaccess_server:latest .

    - name: save image to archive
      run:  docker save goaccess_server:latest > ./goaccess_server.tar

    - name: Upload artifact
      uses: christopherhx/gitea-upload-artifact@v4
      with:
        name: deploy-files
        path: |
          ./goaccess_server.tar
          ./docker-compose.prod.yaml

  deploy:
    name: Deploy on ${{ matrix.environment }}
    runs-on: orange-local
    env:
      SSH_AUTH_SOCK: ./ssh.sock
      KEY: ${{ secrets.REMOTE_KEY }}
    needs: build
    strategy:
      matrix:
        environment: [orange, goaccess-otp]
        include:
        - environment: "orange"
          fingerprint: ${{ secrets.ORANGE_FINGERPRINT }}
          context: deploy-orange
          host: ${{vars.ORANGE_SSH_HOST}}
        - environment: "goaccess-otp"
          fingerprint: ${{ secrets.GO_OTP_FINGERPRINT }}
          host: ${{vars.GO_OTP_SSH_HOST}}
          context: deploy-goaccess-otp

    steps:
    - name: Download artifact
      uses: christopherhx/gitea-download-artifact@v4
      with:
        name: deploy-files

    - name: crete agent
      run: ssh-agent -a $SSH_AUTH_SOCK

    - name: Display structure of downloaded files
      run: ls -Rlt

    - name: add ssh key
      run: echo "$KEY"  | ssh-add -k /dev/stdin

    - name: add fingerprint
      run: grep ${{ matrix.fingerprint }} ~/.ssh/known_hosts 1>/dev/null || echo "${{ matrix.fingerprint }}" >> ~/.ssh/known_hosts

    - run: eval $X || (eval $Y && eval  $X)
      env:
        X: "docker context create --docker host=${{ matrix.host }} ${{ matrix.context }}"
        Y: "docker context rm ${{ matrix.context }} -f"

    - name: list containers
      run: docker --context ${{ matrix.context }} ps -a

    - name: copy image file
      run: cat goaccess_server.tar | docker --context ${{ matrix.context }} load

    - name: deploy
      run: docker --context ${{ matrix.context }} stack deploy -c ./docker-compose.prod.yaml goaccess
