name: Build and deploy
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy on ${{ matrix.environment }}
    runs-on: orange-local
    strategy:
      matrix:
        environment: [orange, goaccess-otp]
        include:
        - environment: "orange"
          goaccess_url: ${{vars.ORANGE_GOACCESS_URL}}
          options: ${{vars.ORANGE_GOACCESS_OPTIONS}}
        - environment: "goaccess-otp"
          goaccess_url: ${{vars.OTP_GOACCESS_URL}}
          options: ${{vars.OTP_GOACCESS_OPTIONS}}


    steps:
    - name: test matrix.goaccess_url
      run: echo ${{matrix.goaccess_url}}
    - name: test matrix.options
      run: echo ${{matrix.options}}
 