on:
  workflow_dispatch:
    input:
      branch:
        description: 'repository branch to run linter on'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - dev

jobs:
  linter:
    runs-on: orange-local
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1

      - name: run linter
        run: |
          docker run --rm -it -v ./:/testing -v ~/.pylintrc:/root/.pylintrc py_tester:latest -m \
          pylint --rcfile=/root/.pylintrc --disable=C --output-format=json /testing/*.py