on:
  workflow_dispatch:

jobs:
  linter:
    runs-on: orange-local
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run linter
        run: docker run --rm -it -v ./:/testing -v ~/.pylintrc:/root/pylintrc py_tester:latest -m pylint --disable=C --output-format=json /testing/*.py
      