name: Update geo database file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * WED'

jobs:
  main:
    runs-on: papaya-runner
    strategy:
      matrix:
        environment: [orange , goaccess-otp]
        include:
        - environment: "orange"
          goaccess_url: ${{vars.ORANGE_GOACCESS_URL}}
          user: orange
        - environment: "goaccess-otp"
          goaccess_url: ${{vars.OTP_GOACCESS_URL}}
          user: root
    steps:
      - name: Run update
        uses: appleboy/ssh-action@v1
        with:
          host: ${{matrix.goaccess_url}}
          username: ${{matrix.user}}
          port: 22
          key: ${{secrets.REMOTE_KEY}}
          script: |
            filename="dbip-country-lite-20$(date +%y)-$(date +%m).mmdb";
            cd /var/geodb;
            wget "https://download.db-ip.com/free/$filename.gz";
            gunzip -c $filename.gz > ./$filename;
            content_type = $(file ./$filename | cut -d' ' -f2 )
            if [ $content_type != "data" ]; then
              echo "Failed downloadning mmdb file =(" >&2; exit 1
            fi
            mv ./$filename ./dbip-lite-latest.mmdb;
            rm -f  ./$filename.gz;
